apiVersion: v1
kind: ConfigMap
metadata:
  name: my-registryconfig
data:
  my-registryconfig: |
    version: 0.1
    log:
      level: error
      formatter: text
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      relativeurls: true
