apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'my-gitlabpostgres-vol'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '5Gi'
  storageClassName: standard
